import * as stylex from '@stylexjs/stylex'
import { media } from '@syneva/design-system/media.stylex'
import { color, font } from '@syneva/design-system/tokens.stylex'

// The product menu's side preview: each link swaps in a tiny scene of what
// its page is about (its lines' motion: preview-motion.styles.ts).
const caption = { font: `9px/1.5 ${font['--mono']}`, color: color['--muted'] }

export const preview = stylex.create({
	frame: {
		position: 'relative',
		minHeight: '286px',
		overflow: 'hidden',
		borderRadius: '5px',
		backgroundColor: color['--paper'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line'],
		display: { default: null, [media.navToggle]: 'none' },
	},
	scene: {
		position: 'absolute',
		inset: 0,
		padding: '18px 18px 36px',
		opacity: 'var(--opacity, 0)',
		transform: {
			default: 'translateY(calc(var(--offset, 0) * 1px))',
			[media.motionReduced]: 'none',
		},
		transition: { default: null, [media.motionReduced]: 'none' },
		pointerEvents: 'none',
		zIndex: { default: null, ':is(.is-current)': 1 },
	},
	caption: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: '6px',
		...caption,
		letterSpacing: '0.035em',
	},
	dot: {
		display: 'inline-block',
		width: '5px',
		height: '5px',
		borderRadius: '50%',
		backgroundColor: color['--green'],
		flexShrink: 0,
	},
	pitch: {
		position: 'absolute',
		bottom: '42px',
		fontSize: '14px',
		lineHeight: 1.5,
		color: color['--muted'],
		letterSpacing: '-0.015em',
	},
	pitchStrong: { color: color['--ink'], fontWeight: 500 },
	example: {
		position: 'absolute',
		bottom: '14px',
		left: '18px',
		fontSize: '10px',
		color: color['--muted'],
	},
	diff: {
		marginTop: '21px',
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line-strong'],
		borderRadius: '4px',
		overflow: 'hidden',
		backgroundColor: color['--white'],
	},
	filename: {
		padding: '10px 11px',
		display: 'flex',
		justifyContent: 'space-between',
		gap: '6px',
		font: `10px/1.5 ${font['--mono']}`,
		borderBottomWidth: '1px',
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line'],
	},
	filenameStat: { color: color['--muted'] },
	code: { padding: '9px 0', font: `10px/1.8 ${font['--mono']}` },
	codeLine: { display: 'block', paddingInline: '11px' },
	minus: {
		backgroundColor: color['--wash'],
		color: color['--accent'],
		textDecoration: 'line-through',
	},
	plus: { backgroundColor: color['--mint'], color: color['--green'] },
	verdict: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'end',
		gap: '5px',
		padding: '8px 11px',
		fontSize: '10px',
		borderTopWidth: '1px',
		borderTopStyle: 'solid',
		borderTopColor: color['--line'],
	},
	check: { color: color['--green'] },
	tree: {
		marginTop: '20px',
		display: 'grid',
		gap: '16px',
		position: 'relative',
		'::before': {
			content: "''",
			position: 'absolute',
			left: '9px',
			top: '12px',
			bottom: '18px',
			width: '1px',
			backgroundColor: color['--line-strong'],
		},
	},
	treeRow: { position: 'relative', paddingLeft: '33px' },
	treeIndex: {
		position: 'absolute',
		left: 0,
		top: '1px',
		backgroundColor: color['--paper'],
		color: color['--accent'],
		font: `10px/1.6 ${font['--mono']}`,
		paddingBlock: '2px',
	},
	treeTitle: {
		display: 'block',
		fontSize: '12px',
		lineHeight: 1.5,
		fontWeight: 500,
	},
	treeFile: {
		display: 'block',
		font: `9px/1.7 ${font['--mono']}`,
		color: color['--muted'],
	},
	conversation: { marginTop: '18px' },
	conversationCode: {
		display: 'block',
		padding: '7px',
		backgroundColor: color['--mint'],
		color: color['--green'],
		font: `10px/1.5 ${font['--mono']}`,
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line'],
	},
	message: {
		marginTop: '11px',
		paddingLeft: '10px',
		borderLeftWidth: '1px',
		borderLeftStyle: 'solid',
		borderLeftColor: color['--line-strong'],
	},
	reply: { borderLeftColor: color['--accent'] },
	who: {
		display: 'block',
		font: `8px/1.5 ${font['--mono']}`,
		color: color['--muted'],
	},
	said: {
		marginTop: '3px',
		fontSize: '11px',
		lineHeight: 1.45,
		color: color['--ink'],
	},
	plan: {
		marginTop: '17px',
		padding: '12px',
		backgroundColor: color['--white'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line-strong'],
	},
	planFile: caption,
	planTitle: {
		display: 'block',
		marginTop: '7px',
		fontSize: '12px',
		lineHeight: 1.45,
		fontWeight: 500,
	},
	planQuestion: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginTop: '10px',
		padding: '7px',
		backgroundColor: color['--wash'],
		color: color['--accent'],
		fontSize: '10px',
		lineHeight: 1.4,
	},
	planMark: { fontSize: '16px' },
})
