import standards from '@nextnode-solutions/standards/oxfmt'
import { defineConfig } from 'oxfmt'

// No extends: spread the shared preset and layer repo-local ignores on top.
export default defineConfig({
	...standards,
	ignorePatterns: [
		...standards.ignorePatterns,
		'node_modules/**',
		'dist/**',
		// GENERATED by packages/frontend/scripts/fetch-icons.mjs.
		'packages/frontend/src/shared/ui/icon-data.ts',
		// GENERATED by Astro.
		'apps/landing/.astro/**',
		// GENERATED by test/benchmarks/bench-dashboard.mjs.
		'test/benchmarks/dashboard.html',
		// Hand-written served prototypes (one file, inline style and script), kept as authored.
		'design/**/*.html',
		// Hand-maintained docs, unformatted per the harness policy.
		'**/*.md',
		'.desk/**',
		'.pi/**',
		'.prd/**',
		'prototypes/**',
		'.playwright-mcp/**',
	],
})
