import standards from '@nextnode-solutions/standards/oxlint'
import { defineConfig } from 'oxlint'

import LANDING_LAYERS from './apps/landing/layers.json' with { type: 'json' }

import type { OxlintOverride } from 'oxlint'

// The layer bans only match aliased imports: these relative spellings close the textual bypass, and the enumerated climbs reach the deepest current nesting.
const relativeLayerEscapes = (...targets: string[]): string[] =>
	targets.flatMap(target => [
		`../${target}`,
		`../${target}/**`,
		`../../${target}/**`,
		`../../../${target}/**`,
		`../../../../${target}/**`,
	])

// Layers run in layers.json order; sliced layers also ban their own alias (intra-slice imports are relative); the rules cover .astro frontmatter/scripts and the React islands (.tsx) too.
const LANDING_SLICED = new Set(['views', 'widgets', 'features', 'entities'])
const LANDING_MOTION_BAN = {
	group: ['motion', 'motion/**'],
	message:
		'the landing animates through @syneva/motion only. Import the engine from @syneva/motion/engine, or export the Motion API you need from it first.',
}
const landingLayer = (layer: string): OxlintOverride => {
	const above = LANDING_LAYERS.slice(0, LANDING_LAYERS.indexOf(layer))
	const others = LANDING_LAYERS.filter(other => other !== layer)
	return {
		files: [`apps/landing/src/${layer}/**/*.{ts,tsx,astro}`],
		rules: {
			'eslint/no-restricted-imports': [
				'error',
				{
					patterns: [
						LANDING_MOTION_BAN,
						...(above.length > 0
							? [
									{
										group: above.flatMap(other => [
											`@${other}`,
											`@${other}/**`,
										]),
										message: `${layer} never imports a layer above it (${above.join(', ')}).`,
									},
								]
							: []),
						...(LANDING_SLICED.has(layer)
							? [
									{
										group: [`@${layer}/**`],
										message: `${layer} slices never import each other; intra-slice imports are relative.`,
									},
								]
							: []),
						{
							group: relativeLayerEscapes(...others),
							message:
								'cross-layer imports use the layer aliases. Relative paths must stay inside the slice.',
						},
					],
				},
			],
		},
	}
}

export default defineConfig({
	extends: [standards],
	// Assigning replaces oxlint's built-in list: node_modules/dist and the generated/runtime artifacts are spelled out.
	ignorePatterns: [
		'node_modules/**',
		'dist/**',
		'.turbo/**',
		// GENERATED by scripts/fetch-icons.mjs.
		'packages/frontend/src/shared/ui/icon-data.ts',
		// GENERATED by Astro.
		'apps/landing/.astro/**',
		'.desk/**',
		'.pi/**',
		'.prd/**',
		'prototypes/**',
		'.playwright-mcp/**',
	],
	overrides: [
		{
			// The drawing/hero figures are data: numbers are coordinates or clock beats, not values to name.
			files: [
				'apps/landing/src/views/*/ui/art/**',
				'apps/landing/src/views/home/ui/circuit/**',
				'apps/landing/src/shared/ui/drawing/**',
				'apps/landing/src/views/home/ui/hero-choreography.ts',
				'apps/landing/src/views/home/ui/hero-timeline.ts',
				'apps/landing/src/views/home/ui/hero-verdict.ts',
				'apps/landing/src/views/home/ui/Hero{Agent,Card,Desk,Ledger,Stage}.astro',
			],
			rules: { 'eslint/no-magic-numbers': 'off' },
		},
		{
			// The landing's copy typesets intended glyphs a visitor reads (never compared as strings): its components, Astro and React (the signup's islands), and these copy modules.
			files: [
				'apps/landing/src/**/*.astro',
				'apps/landing/src/**/*.tsx',
				'apps/landing/src/entities/desk/model/agent-contract.ts',
				'apps/landing/src/views/*/ui/art/*.ts',
			],
			rules: { 'nextnode/no-confusable-chars': 'off' },
		},
		{
			// Assigning to context.locals is Astro's middleware contract, not a param reassignment.
			files: ['apps/landing/src/middleware.ts'],
			rules: { 'eslint/no-param-reassign': 'off' },
		},
		{
			// No Tailwind anywhere; StyleX/DOM keyword strings ('fill-box', 'left center') only look like utility classes to the heuristic.
			files: [
				'apps/landing/**',
				'packages/design-system/**',
				'packages/frontend/**',
				'packages/motion/**',
			],
			rules: { 'nextnode/no-detached-tailwind': 'off' },
		},
		{
			// Unassigned import: CSS is loaded for its side effect (the font faces land in the linked stylesheet).
			files: ['packages/frontend/src/app/*.tsx'],
			rules: {
				'import/no-unassigned-import': [
					'warn',
					{ allow: ['**/*.css'] },
				],
			},
		},
		{
			// A mechanical translation of @pierre's resolveRegion cursor walk: splitting it would scatter the one lockstep-ledger invariant.
			files: ['packages/frontend/src/shared/diff-renderer/distill.ts'],
			rules: {
				'eslint/max-lines-per-function': 'off',
				'eslint/max-depth': 'off',
			},
		},
		{
			// Parallel long-polls would reorder feedback and detach event ownership from delivery.
			files: [
				'packages/backend/src/adapters/inbound/pi/desk-listener.ts',
			],
			rules: { 'eslint/no-await-in-loop': 'off' },
		},
		{
			// Sequential by design: one correspondent event at a time, answers in question order (as the long-poll).
			files: [
				'packages/backend/src/adapters/inbound/pi/pi-attachment.ts',
				'packages/backend/src/adapters/inbound/pi/pi-delivery.ts',
			],
			rules: { 'eslint/no-await-in-loop': 'off' },
		},
		{
			files: ['apps/landing/**'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{ patterns: [LANDING_MOTION_BAN] },
				],
			},
		},
		{
			files: ['packages/motion/src/**/*.ts'],
			excludeFiles: ['packages/motion/src/engine.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: ['motion', 'motion/**'],
								message:
									'engine.ts is the one seam of @syneva/motion onto Motion. Import the engine from ./engine, or export the Motion API you need from it first.',
							},
						],
					},
				],
			},
		},
		...LANDING_LAYERS.map(landingLayer),
		{
			// contracts is a neutral sink; domain is pure (node:crypto stays allowed for pure hashing); the backend never imports the browser and vice versa.
			files: ['packages/contracts/src/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/backend',
									'@syneva/backend/**',
									'@syneva/frontend',
									'@syneva/frontend/**',
								],
								message:
									'contracts is a neutral dependency sink - it imports no backend/frontend module.',
							},
						],
					},
				],
			},
		},
		{
			// A later override replaces the whole rule set for the same files: domain's restrictions live together in ONE declaration.
			files: [
				'packages/backend/src/domain/*.ts',
				'packages/backend/src/domain/**/*.ts',
			],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/contracts',
									'@syneva/contracts/**',
									'../adapters/**',
									'../../adapters/**',
									'../../../adapters/**',
									'../application/**',
									'../../application/**',
									'../../../application/**',
									'../frontend/**',
									'../../frontend/**',
									'../../../frontend/**',
								],
								message:
									'domain is pure - no contracts (shared shapes are re-declared in review.ts), no adapters/application, no UI.',
							},
						],
					},
					{
						patterns: [
							{
								group: ['fs', 'node:fs'],
								message: 'domain is pure - no filesystem.',
							},
							{
								group: ['http', 'node:http'],
								message: 'domain is pure - no HTTP.',
							},
							{
								group: ['child_process', 'node:child_process'],
								message:
									'domain is pure - no process spawning.',
							},
							{
								group: ['net', 'node:net'],
								message: 'domain is pure - no networking.',
							},
							{
								group: ['process', 'node:process'],
								message: 'domain is pure - no process access.',
							},
						],
					},
				],
			},
		},
		{
			// domain is excluded so the stricter pure rule set above is not replaced wholesale.
			files: ['packages/backend/src/**/*.ts'],
			excludeFiles: ['packages/backend/src/domain/**'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/frontend',
									'@syneva/frontend/**',
								],
								message:
									'the backend never imports the browser UI world.',
							},
						],
					},
				],
			},
		},
		{
			// Each layer keeps exactly ONE effective declaration (later overrides replace rules); @features/context is the one deliberate layer seam.
			files: ['packages/frontend/src/shared/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/backend',
									'@syneva/backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: [
									'@app',
									'@app/**',
									'@pages',
									'@pages/**',
									'@widgets',
									'@widgets/**',
									'@features',
									'@features/**',
									'@entities',
									'@entities/**',
								],
								message:
									'shared imports nothing above itself - only other shared modules and @syneva/contracts.',
							},
							{
								group: [
									'../app',
									'../app/**',
									'../../app/**',
									'../../../app/**',
									'../pages',
									'../pages/**',
									'../../pages/**',
									'../../../pages/**',
									'../widgets',
									'../widgets/**',
									'../../widgets/**',
									'../../../widgets/**',
									'../features',
									'../features/**',
									'../../features/**',
									'../../../features/**',
									'../entities',
									'../entities/**',
									'../../entities/**',
									'../../../entities/**',
									'../worker',
									'../worker/**',
									'../../worker/**',
									'../../../worker/**',
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside shared/.',
							},
						],
					},
				],
			},
		},
		{
			files: ['packages/frontend/src/entities/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/backend',
									'@syneva/backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: [
									'@app',
									'@app/**',
									'@pages',
									'@pages/**',
									'@widgets',
									'@widgets/**',
									'@features',
									'@features/**',
								],
								message:
									'entities import shared and entities only - never features/widgets/pages/app.',
							},
							{
								group: ['@entities/**'],
								message:
									'entities never import another entity slice; intra-slice imports are relative.',
							},
							{
								group: [
									...relativeLayerEscapes(
										'app',
										'pages',
										'widgets',
										'features',
										'shared',
										'worker',
									),
									...relativeLayerEscapes('settings'),
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside the entity slice.',
							},
						],
					},
				],
			},
		},
		{
			files: ['packages/frontend/src/features/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/backend',
									'@syneva/backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: [
									'@app',
									'@app/**',
									'@pages',
									'@pages/**',
									'@widgets',
									'@widgets/**',
								],
								message:
									'features import entities/shared only - never widgets/pages/app.',
							},
							{
								group: ['@features/**', '!@features/context'],
								message:
									'features never import another feature slice; intra-slice imports are relative. The layer seam @features/context is the one exception.',
							},
							{
								group: [
									...relativeLayerEscapes(
										'app',
										'pages',
										'widgets',
										'entities',
										'shared',
										'worker',
									),
									...relativeLayerEscapes(
										'decide-change',
										'expand-context',
										'manage-comment',
										'open-editor',
										'send-review',
									),
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside the feature slice.',
							},
						],
					},
				],
			},
		},
		{
			files: ['packages/frontend/src/widgets/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/backend',
									'@syneva/backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: [
									'@app',
									'@app/**',
									'@pages',
									'@pages/**',
								],
								message:
									'widgets import features/entities/shared only - never pages/app.',
							},
							{
								group: ['@widgets/**'],
								message:
									'widgets never import another widget slice; intra-slice imports are relative.',
							},
							{
								group: [
									...relativeLayerEscapes(
										'app',
										'pages',
										'features',
										'entities',
										'shared',
										'worker',
									),
									...relativeLayerEscapes(
										'chrome',
										'dialogs',
									),
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside the widget slice.',
							},
						],
					},
				],
			},
		},
		{
			files: ['packages/frontend/src/pages/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/backend',
									'@syneva/backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: ['@app', '@app/**'],
								message:
									'pages compose widgets/features/entities/shared - they never import app.',
							},
							{
								group: [
									...relativeLayerEscapes(
										'app',
										'widgets',
										'features',
										'entities',
										'shared',
										'worker',
									),
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside pages/.',
							},
							{
								group: ['@pages/**'],
								message:
									'pages never import another page slice; intra-slice imports are relative.',
							},
						],
					},
				],
			},
		},
		{
			// app and the worker are composition roots (import every layer) but never the backend.
			files: [
				'packages/frontend/src/app/**/*.ts',
				'packages/frontend/src/worker/**/*.ts',
			],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'@syneva/backend',
									'@syneva/backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
						],
					},
				],
			},
		},

		{
			// tsgolint cannot resolve the frontend layer aliases (it ignores tsconfig paths), so its type-aware rules fire unsoundly there: the frontend's type gate is tsconfig.ui.json via pnpm check, the backend stays fully type-linted.
			files: [
				'packages/frontend/src/**/*.ts',
				'packages/frontend/src/**/*.tsx',
			],
			rules: {
				'typescript/no-redundant-type-constituents': 'off',
				'typescript/prefer-nullish-coalescing': 'off',
				'typescript/no-unnecessary-condition': 'off',
				'typescript/no-unnecessary-type-assertion': 'off',
				'typescript/require-array-sort-compare': 'off',
			},
		},
		{
			// Composition modules (main.ts wires every slice, render.ts is the one render funnel, diff-instance.ts orchestrates the diff island): splitting them would scatter composition.
			files: [
				'packages/frontend/src/app/main.tsx',
				'packages/frontend/src/pages/desk/render.ts',
				'packages/frontend/src/widgets/diff-view/diff-instance.ts',
			],
			rules: { 'import/max-dependencies': 'off' },
		},
		{
			// The Proxy handlers ARE the wrap/unwrap seam: the type assertions are the seam itself.
			files: [
				'packages/frontend/src/shared/lib/reactive.ts',
				'packages/frontend/src/widgets/chrome/react/settings-descriptors.ts',
			],
			rules: {
				'nextnode/no-type-assertion': 'off',
				'typescript/no-unsafe-type-assertion': 'off',
				// The descriptor table's keys are the domain; the generic only carries the
				// write boundary.
				'typescript/no-unnecessary-type-parameters': 'off',
			},
		},
		{
			// The React chrome is a view over the mutable reactive store (useSyncExternalStore): handler-side writes are the designed mutation path; the effects sync external systems that are not render derivations.
			files: [
				'packages/frontend/src/widgets/chrome/react/**',
				'packages/frontend/src/widgets/hub-shell/react/**',
				'packages/frontend/src/pages/dashboard/**/*.tsx',
				'packages/frontend/src/entities/hub/use-hub.ts',
				'packages/frontend/src/pages/dashboard/use-document-title.ts',
				'packages/frontend/src/pages/dashboard/use-new-review-shortcut.ts',
				'packages/frontend/src/pages/dashboard/use-escape-to-disarm.ts',
				'packages/frontend/src/pages/dashboard/use-focus-next.ts',
				'packages/frontend/src/app/react/app.tsx',
			],
			rules: {
				'react/immutability': 'off',
				// Row/action fragments live in one file, where only together do they make sense.
				'react/no-multi-comp': 'off',
				'nextnode/no-use-effect': 'off',
			},
		},
		{
			// The fixtures encode the workload by design (an 8k-line giant, a 2.4MB oversized file) and report through console.log; sequenced awaits ARE the measurement, so no parallelizing.
			files: [
				'test/benchmarks/bench-fixtures.mjs',
				'test/benchmarks/browser-bench.mjs',
				'test/benchmarks/perf-smoke.mjs',
			],
			rules: {
				'eslint/no-magic-numbers': 'off',
				'eslint/no-console': 'off',
				'eslint/max-lines': 'off',
				'eslint/max-lines-per-function': 'off',
				'eslint/max-depth': 'off',
				'nextnode/no-nullish-ternary-return': 'off',
				// The instruments reach into syneva's own store singleton by the underscore convention.
				'eslint/no-underscore-dangle': 'off',
				'eslint/no-await-in-loop': 'off',
				// Best-effort cleanup and read probes swallow expected failures.
				'eslint/no-empty': 'off',
			},
		},
		{
			// The landing Worker's one log boundary, as adapters/outbound/console.ts is the backend's: Workers Logs-style JSON.
			files: [
				'apps/landing/src/features/subscribe/model/log-failure.server.ts',
			],
			rules: { 'eslint/no-console': 'off' },
		},
		{
			// pi's loader contract: the entry default-exports register.
			files: ['apps/syneva/extension/syneva.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
		{
			// It types the shared preset's default export itself.
			files: ['types/**/*.d.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
	],
})
