import { deskText } from '@shared/ui/desk.stylex'
import * as stylex from '@stylexjs/stylex'
import { color, font } from '@syneva/design-system/tokens.stylex'

export const block = stylex.create({
	card: {
		marginBottom: '14px',
		backgroundColor: color['--white'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line'],
	},
	failed: { borderColor: color['--amber-line'] },
	head: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		paddingBlock: '7px',
		paddingInline: '10px',
		borderBottomWidth: '1px',
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line'],
	},
	kind: {
		fontFamily: font['--mono'],
		fontSize: deskText.label,
		letterSpacing: '.08em',
		textTransform: 'uppercase',
		color: color['--muted'],
	},
	title: {
		minWidth: 0,
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		whiteSpace: 'nowrap',
		fontSize: deskText.title,
		fontWeight: 500,
		color: color['--ink'],
	},
	actions: { marginLeft: 'auto', display: 'flex', gap: '4px' },
	body: {
		paddingBlock: '10px',
		paddingInline: '12px',
		fontSize: deskText.title,
		lineHeight: 1.6,
		color: color['--ink'],
	},
	prose: { overflowWrap: 'break-word' },
	foot: {
		paddingBlock: '6px',
		paddingInline: '12px',
		paddingBottom: '10px',
		borderTopWidth: '1px',
		borderTopStyle: 'solid',
		borderTopColor: color['--line'],
		fontSize: deskText.body,
	},
	refs: {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		gap: '6px',
	},
	refsLabel: {
		marginRight: '2px',
		fontFamily: font['--mono'],
		fontSize: deskText.label,
		letterSpacing: '.08em',
		textTransform: 'uppercase',
		color: color['--muted'],
	},
	detail: { marginTop: '6px' },
	detailSummary: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: '6px',
		cursor: 'pointer',
		listStyle: 'none',
		fontSize: deskText.small,
		fontWeight: 500,
		color: color['--accent'],
	},
	detailBody: { marginTop: '6px', fontSize: deskText.body, lineHeight: 1.6 },
	failNote: {
		paddingBlock: '6px',
		paddingInline: '10px',
		borderTopWidth: '1px',
		borderTopStyle: 'dashed',
		borderTopColor: color['--amber-line'],
		fontSize: deskText.small,
		color: color['--amber'],
	},
	beforeAfter: {
		display: 'grid',
		gridTemplateColumns: '1fr 1fr',
		gap: '1px',
		backgroundColor: color['--line'],
	},
	side: {
		paddingBlock: '8px',
		paddingInline: '10px',
		backgroundColor: color['--white'],
		fontSize: deskText.body,
		lineHeight: 1.6,
	},
	sideLabel: {
		display: 'block',
		marginBottom: '4px',
		fontFamily: font['--mono'],
		fontSize: deskText.label,
		letterSpacing: '.08em',
		textTransform: 'uppercase',
	},
	before: { color: color['--red'] },
	after: { color: color['--green'] },
	sideRef: { marginTop: '6px' },
})
