// The keys the guide schema knows, per object. Nothing an agent writes is silently ignored: a key outside its object's list is refused by name (guide-parse.ts onlyKeys), so a typo in an optional field cannot drop it. A new field is an entry here and its reader, never a silent passthrough.
export const GUIDE_KEYS = {
	guide: ['format', 'source', 'overview', 'domains', 'baseDiffHash'],
	source: ['mode', 'fingerprint', 'head', 'base', 'staged', 'path'],
	domain: [
		'id',
		'title',
		'risk',
		'consequence',
		'summary',
		'verify',
		'prerequisites',
		'members',
		'references',
		'related',
		'evidence',
		'unknowns',
		'blocks',
		'order',
	],
	changeMember: ['kind', 'path', 'side', 'lineNumber', 'endLine'],
	fileMember: ['kind', 'path'],
	reference: ['id', 'path', 'side', 'lineNumber', 'endLine', 'role', 'label'],
	related: ['domainId', 'note'],
	evidence: ['text', 'refs'],
	block: ['id', 'kind', 'title', 'refs', 'detail'],
	prose: ['markdown'],
	beforeAfter: ['before', 'after'],
	side: ['label', 'markdown', 'ref'],
	state: ['states', 'transitions'],
	stateNode: ['id', 'label', 'ref', 'isInitial', 'isFinal'],
	transition: ['from', 'to', 'label', 'ref'],
	sequence: ['participants', 'steps'],
	participant: ['id', 'label'],
	step: ['from', 'to', 'label', 'ref'],
	flow: ['nodes', 'edges'],
	flowNode: ['id', 'label', 'ref', 'note'],
	flowEdge: ['from', 'to', 'label'],
} as const
