import { deskText } from '@shared/ui/desk.stylex'
import * as stylex from '@stylexjs/stylex'
import { color, font } from '@syneva/design-system/tokens.stylex'

export const navigator = stylex.create({
	overview: {
		paddingBlock: '6px',
		paddingInline: '8px',
		paddingBottom: '10px',
		borderBottomWidth: '1px',
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line'],
	},
	intent: {
		marginTop: '4px',
		marginBottom: '6px',
		marginInline: 0,
		fontSize: deskText.body,
		lineHeight: 1.5,
		color: color['--ink'],
		display: '-webkit-box',
		WebkitLineClamp: 3,
		WebkitBoxOrient: 'vertical',
		overflow: 'hidden',
	},
	cover: {
		display: 'flex',
		gap: '10px',
		fontFamily: font['--mono'],
		fontSize: deskText.small,
		color: color['--muted'],
	},
	coverCount: { color: color['--ink'], fontWeight: 500 },
	row: {
		display: 'block',
		width: '100%',
		paddingBlock: '8px',
		paddingInline: '8px',
		paddingLeft: '10px',
		borderWidth: 0,
		borderStyle: 'solid',
		borderLeftWidth: '2px',
		borderLeftColor: 'transparent',
		backgroundColor: { default: 'transparent', ':hover': color['--field'] },
		textAlign: 'left',
		fontFamily: font['--sans'],
		color: color['--ink'],
		cursor: 'pointer',
		outlineOffset: '-2px',
	},
	current: {
		borderLeftColor: color['--accent'],
		backgroundColor: {
			default: color['--wash'],
			':hover': color['--wash'],
		},
	},
	top: { display: 'flex', alignItems: 'center', gap: '8px' },
	index: {
		fontFamily: font['--mono'],
		fontSize: deskText.label,
		color: color['--muted'],
	},
	title: {
		flex: '1 1 auto',
		minWidth: 0,
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		whiteSpace: 'nowrap',
		fontSize: '12.5px',
		fontWeight: 500,
	},
	consequence: {
		marginTop: '3px',
		marginBottom: 0,
		marginInline: 0,
		fontSize: deskText.small,
		lineHeight: 1.45,
		color: color['--muted'],
		display: '-webkit-box',
		WebkitLineClamp: 2,
		WebkitBoxOrient: 'vertical',
		overflow: 'hidden',
	},
	meter: {
		position: 'relative',
		marginTop: '6px',
		height: '3px',
		backgroundColor: color['--line'],
	},
	meterDone: {
		position: 'absolute',
		insetBlock: 0,
		left: 0,
		backgroundColor: color['--green'],
	},
	meterRejected: {
		position: 'absolute',
		insetBlock: 0,
		left: 0,
		backgroundColor: color['--amber'],
	},
	foot: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginTop: '4px',
		fontFamily: font['--mono'],
		fontSize: deskText.label,
		color: color['--muted'],
	},
	unassigned: {
		marginTop: '10px',
		paddingBlock: '8px',
		paddingInline: '10px',
		borderWidth: '1px',
		borderStyle: 'dashed',
		borderColor: color['--amber-line'],
		backgroundColor: color['--amber-tint'],
		color: color['--amber'],
		fontSize: deskText.small,
		lineHeight: 1.45,
	},
	unassignedTitle: { display: 'block', fontWeight: 600, marginBottom: '4px' },
	unassignedRow: {
		display: 'flex',
		gap: '6px',
		width: '100%',
		paddingBlock: '3px',
		paddingInline: 0,
		borderWidth: 0,
		borderStyle: 'none',
		backgroundColor: 'transparent',
		textAlign: 'left',
		fontFamily: font['--mono'],
		fontSize: deskText.small,
		color: color['--amber'],
		cursor: 'pointer',
		textDecoration: { default: 'none', ':hover': 'underline' },
	},
	otherLabel: {
		marginTop: '12px',
		marginBottom: '4px',
		paddingInline: '8px',
	},
})
