// Regenerates src/shared/ui/icon-data.ts by inlining SVGs from the Iconify API (edit ICON_MAP, re-run): committed inline keeps zero runtime dependencies and no runtime network.
import { writeFileSync } from 'node:fs'

// Lucide: clean line set, icons inherit currentColor; editor-grade coverage of every primitive needed.
const ICON_MAP = {
	'gly-chevron': 'lucide:chevron-right',
	'gly-folder': 'lucide:folder',
	'gly-file': 'lucide:file',
	'gly-check': 'lucide:circle-check',
	'gly-flag': 'lucide:flag',
	'gly-collapse-all': 'lucide:chevrons-up',
	'gly-expand-all': 'lucide:chevrons-down',
	'gly-settings': 'lucide:settings',
	'gly-home': 'lucide:house',
	'gly-arrow-left': 'lucide:arrow-left',
	'gly-arrow-right': 'lucide:arrow-right',
	'gly-warn': 'lucide:triangle-alert',
	'gly-open-editor': 'lucide:square-arrow-out-up-right',
	'gly-comment': 'lucide:message-square',
	'gly-circle': 'lucide:circle',
	'gly-circle-alert': 'lucide:circle-alert',
	'gly-menu': 'lucide:menu',
	'gly-close': 'lucide:x',
}

// 1.5 stroke: Lucide ships 2 units; lighter sits with the site's thin rules.
const STROKE_WIDTH = '1.5'

// Hand-drawn glyphs with no library equivalent (status primitives); 24-unit viewBox matches the fetched set so they scale identically.
const CUSTOM = {
	'gly-dot': {
		vb: '0 0 24 24',
		body: `<rect x="8" y="8" width="8" height="8" fill="currentColor"/>`,
	},
}

async function fetchIcon(id) {
	const [prefix, name] = id.split(':')
	const res = await fetch(`https://api.iconify.design/${prefix}/${name}.svg`)
	if (!res.ok) throw new Error(`${id}: HTTP ${res.status}`)
	const svg = await res.text()
	const vb = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 24 24'
	const body = svg
		.replace(/^[\s\S]*?<svg[^>]*>/, '')
		.replace(/<\/svg>\s*$/, '')
		.replaceAll('stroke-width="2"', `stroke-width="${STROKE_WIDTH}"`)
		.trim()
	return { vb, body }
}

const out = { ...CUSTOM }
const fetched = await Promise.all(
	Object.entries(ICON_MAP).map(async ([gly, id]) => {
		process.stdout.write(`  ${gly} <- ${id}\n`)
		return [gly, await fetchIcon(id)]
	}),
)
for (const [gly, icon] of fetched) out[gly] = icon

const JSON_INDENT = 2
const header =
	`// GENERATED by scripts/fetch-icons.mjs - do not edit by hand.\n` +
	`// Inlined SVG bodies (currentColor, duotone) for the icon sprite; re-run the script to swap sets.\n`
writeFileSync(
	new URL('../src/shared/ui/icon-data.ts', import.meta.url),
	`${header}export const ICON_DATA: Record<string, { vb: string; body: string }> = ${JSON.stringify(out, null, JSON_INDENT)};\n`,
)
process.stdout.write('wrote src/shared/ui/icon-data.ts\n')
