import { deskText } from '@shared/ui/desk.stylex'
import * as stylex from '@stylexjs/stylex'
import { color, font } from '@syneva/design-system/tokens.stylex'

export const overview = stylex.create({
	page: {
		minHeight: '100%',
		display: 'grid',
		alignItems: 'start',
		justifyItems: 'center',
		paddingBlock: '48px',
		paddingInline: '30px',
		backgroundColor: color['--paper'],
		backgroundImage: `linear-gradient(${color['--grid']} 1px, transparent 1px), linear-gradient(90deg, ${color['--grid']} 1px, transparent 1px)`,
		backgroundSize: '48px 48px',
	},
	card: {
		width: 'min(680px, 100%)',
		paddingBlock: '24px',
		paddingInline: '28px',
		backgroundColor: color['--white'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line-strong'],
	},
	title: {
		marginTop: 0,
		marginInline: 0,
		marginBottom: '6px',
		fontFamily: font['--sans'],
		fontSize: '26px',
		fontWeight: 500,
		letterSpacing: '-.035em',
		lineHeight: 1.1,
		color: color['--ink'],
	},
	sub: { marginBottom: '18px' },
	stale: {
		marginTop: '12px',
		marginBottom: '18px',
		paddingBlock: '8px',
		paddingInline: '11px',
		backgroundColor: color['--amber-tint'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--amber-line'],
		fontSize: deskText.body,
		lineHeight: 1.45,
		color: color['--amber'],
	},
	unassigned: {
		display: 'flex',
		alignItems: 'center',
		gap: '6px',
		marginBottom: '18px',
		paddingBlock: '8px',
		paddingInline: '11px',
		backgroundColor: color['--white'],
		borderWidth: '1px',
		borderStyle: 'dashed',
		borderColor: color['--amber-line'],
		fontSize: deskText.body,
		color: color['--amber'],
	},
	staleCode: {
		paddingInline: '4px',
		fontFamily: font['--mono'],
		backgroundColor: color['--white'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line'],
	},
	intent: {
		marginBottom: '18px',
		fontSize: deskText.title,
		lineHeight: 1.6,
		color: color['--ink'],
	},
	label: { marginBottom: '8px' },
	domains: {
		listStyle: 'none',
		margin: 0,
		marginBottom: '20px',
		padding: 0,
		borderTopWidth: '1px',
		borderTopStyle: 'solid',
		borderTopColor: color['--line'],
	},
	domain: {
		paddingBlock: '9px',
		borderBottomWidth: '1px',
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line'],
	},
	domainButton: {
		display: 'block',
		width: '100%',
		padding: 0,
		borderWidth: 0,
		borderStyle: 'none',
		backgroundColor: 'transparent',
		textAlign: 'left',
		color: color['--ink'],
		cursor: 'pointer',
		outlineOffset: '2px',
	},
	domainHead: {
		display: 'flex',
		alignItems: 'center',
		gap: '10px',
	},
	domainTitle: {
		fontSize: deskText.title,
		fontWeight: 500,
		color: color['--ink'],
	},
	domainFiles: { marginLeft: 'auto', whiteSpace: 'nowrap' },
	consequence: {
		marginTop: '4px',
		marginBottom: 0,
		marginInline: 0,
		fontSize: deskText.body,
		lineHeight: 1.5,
		color: color['--muted'],
	},
	actions: {
		display: 'flex',
		alignItems: 'center',
		gap: '12px',
	},
})
