import { deskText } from '@shared/ui/desk.stylex'
import * as stylex from '@stylexjs/stylex'
import { color, font } from '@syneva/design-system/tokens.stylex'

export const discussion = stylex.create({
	thread: {
		marginBottom: '10px',
		backgroundColor: color['--white'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line'],
	},
	threadResolved: { opacity: 0.7 },
	head: {
		display: 'flex',
		alignItems: 'center',
		flexWrap: 'wrap',
		gap: '6px',
		paddingBlock: '6px',
		paddingInline: '10px',
		borderBottomWidth: '1px',
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line'],
		fontSize: deskText.small,
		color: color['--muted'],
	},
	target: { fontWeight: 500, color: color['--ink'] },
	message: {
		paddingBlock: '8px',
		paddingInline: '10px',
		borderBottomWidth: '1px',
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line'],
		fontSize: deskText.body,
		lineHeight: 1.5,
	},
	messageAgent: { backgroundColor: color['--wash'] },
	meta: {
		display: 'flex',
		alignItems: 'center',
		gap: '6px',
		marginBottom: '4px',
		fontFamily: font['--mono'],
		fontSize: deskText.label,
		letterSpacing: '.06em',
		textTransform: 'uppercase',
		color: color['--muted'],
	},
	author: { color: color['--ink'] },
	authorAgent: { color: color['--accent'] },
	waiting: {
		paddingBlock: '6px',
		paddingInline: '10px',
		fontSize: deskText.small,
		color: color['--muted'],
	},
	foot: {
		display: 'flex',
		gap: '4px',
		paddingBlock: '6px',
		paddingInline: '10px',
	},
	composer: {
		marginBottom: '10px',
		paddingBlock: '8px',
		paddingInline: '10px',
		backgroundColor: color['--white'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--accent-line'],
	},
	composerLabel: {
		display: 'block',
		marginBottom: '6px',
		fontSize: deskText.small,
		color: color['--muted'],
	},
	textarea: {
		display: 'block',
		width: '100%',
		minHeight: '72px',
		boxSizing: 'border-box',
		padding: '8px',
		resize: 'vertical',
		fontFamily: font['--sans'],
		fontSize: deskText.body,
		lineHeight: 1.5,
		color: color['--ink'],
		backgroundColor: color['--paper'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: { default: color['--line'], ':focus': color['--accent'] },
		outline: 'none',
	},
	actions: {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '4px',
		marginTop: '6px',
	},
	empty: {
		fontSize: deskText.body,
		lineHeight: 1.5,
		color: color['--muted'],
	},
})
