import { deskText } from '@shared/ui/desk.stylex'
import * as stylex from '@stylexjs/stylex'
import { media } from '@syneva/design-system/media.stylex'
import { color, font } from '@syneva/design-system/tokens.stylex'

const PAD = '14px'

export const pane = stylex.create({
	aside: {
		minWidth: 0,
		minHeight: 0,
		display: 'flex',
		flexDirection: 'column',
		overflow: 'hidden',
		backgroundColor: color['--paper'],
		// Under the tablet width the pane stacks under the guide bar, above the diff: its height is capped, its body scrolls, the diff keeps the rest.
		flexShrink: { default: null, [media.tablet]: 0 },
		maxHeight: { default: null, [media.tablet]: 'min(44vh, 440px)' },
		borderBottomWidth: { default: 0, [media.tablet]: '1px' },
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line-strong'],
	},
	head: {
		flexShrink: 0,
		paddingBlock: '10px',
		paddingInline: PAD,
		borderBottomWidth: '1px',
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line'],
	},
	row: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		flexWrap: 'wrap',
	},
	position: {
		fontFamily: font['--mono'],
		fontSize: deskText.label,
		letterSpacing: '.08em',
		textTransform: 'uppercase',
		color: color['--muted'],
	},
	navs: { marginLeft: 'auto', display: 'flex', gap: '4px' },
	title: {
		marginTop: '6px',
		marginBottom: '4px',
		marginInline: 0,
		fontSize: deskText.display,
		fontWeight: 500,
		letterSpacing: '-.03em',
		lineHeight: 1.25,
		color: color['--ink'],
	},
	summary: {
		margin: 0,
		fontSize: deskText.title,
		lineHeight: 1.6,
		color: color['--ink'],
	},
	consequence: {
		marginTop: '10px',
		paddingBlock: '7px',
		paddingInline: '11px',
		backgroundColor: color['--white'],
		borderLeftWidth: '2px',
		borderLeftStyle: 'solid',
		borderLeftColor: color['--line-strong'],
		fontSize: deskText.body,
		lineHeight: 1.5,
		color: color['--ink'],
	},
	consequenceCritical: { borderLeftColor: color['--red-line'] },
	consequenceHigh: { borderLeftColor: color['--amber-line'] },
	consequenceMedium: { borderLeftColor: color['--accent-line'] },
	verify: { borderLeftColor: color['--green-line'] },
	label: {
		display: 'block',
		marginBottom: '2px',
		fontFamily: font['--mono'],
		fontSize: deskText.label,
		letterSpacing: '.08em',
		textTransform: 'uppercase',
		color: color['--muted'],
	},
	stale: {
		display: 'flex',
		gap: '8px',
		alignItems: 'flex-start',
		marginTop: '10px',
		marginInline: PAD,
		paddingBlock: '8px',
		paddingInline: '11px',
		backgroundColor: color['--amber-tint'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--amber-line'],
		fontSize: deskText.small,
		lineHeight: 1.45,
		color: color['--amber'],
	},
	body: {
		flex: '1 1 auto',
		minHeight: 0,
		overflow: 'auto',
		paddingBlock: '12px',
		paddingInline: PAD,
		paddingBottom: '24px',
	},
	section: { marginBottom: '16px' },
	sectionLabel: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		marginBottom: '6px',
	},
	count: {
		letterSpacing: 0,
		textTransform: 'none',
		color: color['--ink'],
	},
	trail: { marginLeft: 'auto' },
	card: {
		paddingBlock: '8px',
		paddingInline: '10px',
		backgroundColor: color['--white'],
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: color['--line'],
		fontSize: deskText.body,
		lineHeight: 1.5,
	},
	link: {
		padding: 0,
		borderWidth: 0,
		borderStyle: 'none',
		backgroundColor: 'transparent',
		fontFamily: font['--sans'],
		fontSize: deskText.body,
		fontWeight: 500,
		color: color['--accent'],
		cursor: 'pointer',
		textDecoration: { default: 'none', ':hover': 'underline' },
		textUnderlineOffset: '3px',
	},
	list: { margin: 0, padding: 0, listStyle: 'none' },
	claim: {
		display: 'flex',
		gap: '8px',
		alignItems: 'baseline',
		paddingBlock: '5px',
		borderBottomWidth: '1px',
		borderBottomStyle: 'solid',
		borderBottomColor: color['--line'],
		fontSize: deskText.body,
		lineHeight: 1.5,
		color: color['--ink'],
	},
	claimMark: {
		flexShrink: 0,
		width: '6px',
		height: '6px',
		backgroundColor: color['--accent'],
	},
	unknownMark: { backgroundColor: color['--line-strong'] },
	empty: {
		paddingBlock: '20px',
		paddingInline: PAD,
		fontSize: deskText.body,
		lineHeight: 1.6,
		color: color['--muted'],
	},
})

export const coverage = stylex.create({
	row: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		width: '100%',
		paddingBlock: '5px',
		paddingInline: '8px',
		borderWidth: '1px',
		borderStyle: 'solid',
		borderColor: { default: 'transparent', ':hover': color['--line'] },
		backgroundColor: {
			default: 'transparent',
			':hover': color['--white'],
		},
		textAlign: 'left',
		fontFamily: font['--mono'],
		fontSize: '11.5px',
		color: color['--ink'],
		cursor: 'pointer',
	},
	current: {
		borderColor: color['--accent-line'],
		backgroundColor: {
			default: color['--wash'],
			':hover': color['--wash'],
		},
	},
	path: {
		display: 'flex',
		minWidth: 0,
		whiteSpace: 'nowrap',
	},
	dir: {
		minWidth: 0,
		overflow: 'hidden',
		textOverflow: 'ellipsis',
		color: color['--muted'],
	},
	name: { flexShrink: 0 },
	lines: { color: color['--muted'], whiteSpace: 'nowrap' },
	verdict: { marginLeft: 'auto' },
})
