// Generated by @nextnode-solutions/worker-types - do not edit.
// Regenerate with `worker-types gen`; source of truth is nextnode.toml.

/// <reference types="@cloudflare/workers-types" />

declare namespace Cloudflare {
	interface Env {
		readonly ASSETS: Fetcher
		readonly D1_DATABASE_ID: string
		readonly DB: D1Database
		readonly RL_SUBSCRIBE: RateLimit
		readonly SITE_URL: string
	}
}

interface Env extends Cloudflare.Env {}
