// Generated by @nextnode-solutions/worker-types; regenerate with `worker-types gen` (source of truth: nextnode.toml). Do not edit.

/// <reference types="@cloudflare/workers-types" />

declare namespace Cloudflare {
	interface Env {
		readonly ASSETS: Fetcher
		readonly D1_DATABASE_ID: string
		readonly DB: D1Database
		readonly RESEND_API_KEY: string
		readonly RL_SUBSCRIBE: RateLimit
		readonly SITE_URL: string
	}
}

interface Env extends Cloudflare.Env {}
