// Assemble the landing deploy bundle for the cloudflare-workers target:
// the static site at dist/ (the assets root the infra derives from the
// _worker.js entry), a pass-through worker under dist/_worker.js/ for
// requests that miss a static file, and a static /healthz for the
// pipeline's smoke check.
//
// Run: pnpm build:landing   (part of pnpm build)
import { cp, mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const SITE_DIR = path.join(REPO_ROOT, 'site')
const DIST_DIR = path.join(REPO_ROOT, 'dist')
const WORKER_DIR = path.join(DIST_DIR, '_worker.js')

// Pass-through only: requests matching a static file are served directly by
// the assets binding (the worker is never invoked); anything else (404s,
// paths without a file) falls through to the script, which hands back to
// ASSETS so error handling stays Cloudflare-native.
const WORKER = `// Generated by scripts/build-landing.mjs - do not edit.
export default {
	fetch: (request, env) => env.ASSETS.fetch(request),
}
`

await rm(DIST_DIR, { recursive: true, force: true })
await mkdir(WORKER_DIR, { recursive: true })
// Ship the site content only - the site/ folder also carries authoring docs
// (.impeccable, AGENTS.md, DESIGN.md) that must not deploy.
await cp(SITE_DIR, DIST_DIR, {
	recursive: true,
	filter: src => {
		const rel = path.relative(SITE_DIR, src)
		return !['.impeccable', 'AGENTS.md', 'DESIGN.md'].includes(rel)
	},
})
await writeFile(path.join(WORKER_DIR, 'index.mjs'), WORKER)
await writeFile(path.join(DIST_DIR, 'healthz'), 'ok\n')
// Wrangler refuses an assets root that contains a `_worker.js/` directory
// (the Pages convention - uploading it would expose the worker source as
// public assets). The code ships via the config's `main`, not the assets
// upload, so excluding it here is what lets the deploy pass; an empty
// .assetsignore would upload the source instead.
await writeFile(path.join(DIST_DIR, '.assetsignore'), '_worker.js\n')
// The build is CI's only signal for the landing bundle - a silent pass/fail
// line, not console noise.
process.stdout.write('landing bundle assembled in dist/\n')
