import { partAttribute } from '@shared/lib/part-attribute'

// Pieces named once: markup marks with stagePart(), the timeline and pointer select with stagePartSelector() - a one-side-only name fails astro check.
export type StagePart =
	| 'agent'
	| 'desk'
	| 'ledger'
	| 'card'
	| 'bar'
	| 'rail'
	| 'rail-dots'
	| 'more'
	| 'focus'
	| 'rev'
	| 'idle'
	| 'caret'
	| 'head'
	| 'accept'
	| 'accept-glyph'
	| 'row'
	| 'strike'
	| 'band-removed'
	| 'band-added'
	| 'sweep'
	| 'gutter-check'
	| 'chip'
	| 'leader'
	| 'thread'
	| 'you'
	| 'typing'
	| 'typing-dot'
	| 'agent-says'
	| 'cursor'
	| 'signal-in'
	| 'signal-out'
	| 'signal-back'
	| 'round-1'
	| 'round-2'
	| 'verdict'
	| 'row-pending'
	| 'fill'
	| 'progress-1'
	| 'progress-2'
	| 'send-box'
	| 'send-label'
	| 'send-sent'

export const { mark: stagePart, selector: stagePartSelector } =
	partAttribute<StagePart>('data-stage-part')
