import { existsSync, promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// The served UI assets sit next to the bundled server (dist/) in an install: the
// apps/syneva assembly bundles cli.js and copies the UI assets into the same
// dist/. Under `pnpm dev` the CLI runs from source via tsx, so __dirname is under
// packages/backend/src - walk up the ancestors until a directory actually holds
// ui.js (always true for the bundled server), else fall back to the assembled
// apps/syneva/dist via process.cwd() (dev.mjs runs tsx from the app package).
async function compiledRoot(): Promise<string> {
	let dir = __dirname
	for (;;) {
		if (existsSync(path.join(dir, 'ui.js'))) return dir
		const parent = path.dirname(dir)
		if (parent === dir) break
		dir = parent
	}
	// No built bundle anywhere above us (source run, assets not built yet): fall through to the
	// caller's per-candidate fallbacks.
	return __dirname
}

// Resolve a UI asset against the built location first, then a dev fallback.
// `first` is also the fallback, so every call stays total without an index
// access that noUncheckedIndexedAccess would doubt.
async function firstExisting(
	first: string,
	...rest: string[]
): Promise<string> {
	for (const candidate of [first, ...rest])
		if (await exists(candidate)) return candidate
	return first
}

async function exists(file: string): Promise<boolean> {
	return await fs.stat(file).then(
		() => true,
		() => false,
	)
}

// One asset by its dist-relative name (ui.js, dashboard.js, index.html, dashboard.html,
// chunks/<name>): the built root first, the assembled app dist second.
async function assetPath(...segments: string[]): Promise<string> {
	return firstExisting(
		path.join(await compiledRoot(), ...segments),
		path.join(process.cwd(), 'dist', ...segments),
	)
}

export function uiBundlePath(): Promise<string> {
	return assetPath('ui.js')
}

export function dashboardBundlePath(): Promise<string> {
	return assetPath('dashboard.js')
}

// Chunk names are generated by the bundler, never arbitrary filesystem paths from a request.
export function uiChunkPath(name: string): Promise<string> {
	return assetPath('chunks', name)
}

// The desk page (served under /d/<id>/) and the dashboard page (the hub root).
export function indexHtmlPath(): Promise<string> {
	return assetPath('index.html')
}

export function dashboardHtmlPath(): Promise<string> {
	return assetPath('dashboard.html')
}
