import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Assembly copies the built UI next to the bundled server; a hub run from source has none beside it - the dev loop serves the pages from source through its own UiServer (routes/static.ts).
function assetPath(...segments: string[]): string {
	return path.join(__dirname, ...segments)
}

export function uiBundlePath(): string {
	return assetPath('ui.js')
}

export function dashboardBundlePath(): string {
	return assetPath('dashboard.js')
}

export function stylesPath(): string {
	return assetPath('styles.css')
}

// Font names are the design system's file names (validated by the route), never arbitrary filesystem paths from a request.
export function fontPath(name: string): string {
	return assetPath('fonts', name)
}

// Chunk names are generated by the bundler, never arbitrary filesystem paths from a request.
export function uiChunkPath(name: string): string {
	return assetPath('chunks', name)
}

export function indexHtmlPath(): string {
	return assetPath('index.html')
}

export function dashboardHtmlPath(): string {
	return assetPath('dashboard.html')
}
